server:
  port: 84

spring:
  profiles:
    active: @profile.active@


# yml 配置文件语法

# 对象
user:
  name: chenbenbuyi
  age: 30

# 数组
arr:
  - v1
  - v2
  - v3

# 同文件多模块配置，用 --- 分割,在默认配置中激活即可

---
server:
  port: 9999
spring:
  profiles: dev

---
server:
  port: 5555
spring:
  profiles: prod