spring:
  activiti:
    async-executor-activate: true
    # activiti 对数据库中的表进行更新，如果不存在，则创建(线上一般用false)
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true

  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai


logging:
  level:
    root: info