server:
  port: 82

spring:
  datasource:
    # spring boot 2.0开始默认支持的数据源连接池，可不配置，除非要使用自定义的如 com.alibaba.druid.pool.DruidDataSource进行替换
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      # 设置默认数据库，即项目中不用显示指定数据库源时使用的数据库
      primary: db1
      datasource:
        # 以下分别配置的两个不同的数据源示例： mysql 和 sqlite
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/hello-boot?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
          username: root
          password:
          hikari:
            idle-timeout: 50000
            connection-timeout: 5000
            minimum-idle: 5
          schema:
             - "classpath:db/schema.sql"
          data:
             - "classpath:db/data_mysql.sql"

        db2:
          driver-class-name: org.sqlite.JDBC
          url: jdbc:sqlite:D:\test.db
          schema:
             - "classpath:db/schema_sqlite.sql"
          data:
             - "classpath:db/data_sqlite.sql"


