spring:
  mail:
    # 需要在邮箱设置中开启SMTP服务并获取授权码
    password: SBIRSCKEEACSVXJS
    # 邮箱设置中显示的服务器地址
    host: smtp.126.com
    username: jicky2008chen@126.com
#    properties: mail.smtp.ssl.enable=true

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hello-boot?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai


