server:
  port: 91
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/hello-boot?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    hikari:
        idle-timeout: 50000
        connection-timeout: 5000
        minimum-idle: 5
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    schema:
       - "classpath:db/schema.sql"
    data:
       - "classpath:db/data.sql"

# redis 配置 无特殊改变，默认就好



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
   # 配置mybatis-plus 扫描枚举类的包路径
  type-enums-package: cnblogs.chenbenbuyi.enums
  configuration:
    # sql 打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
