server:
  port: 92

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    initialization-mode: always
    schema:
      - "classpath:db/schema.sql"
    data:
      - "classpath:db/data.sql"


logging:
  level:
    root: info
    cnblogs.chenbenbuyi.service: info
    cnblogs.chenbenbuyi: warn
