server:
  port: 89
dubbo:
  application:
    name: spring-boot-dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  scan:
    base-packages: cnblogs.chenbenbuyi.service